name: "HugoGiraudel.com"
description: "I write about front-end development stuff."
url: "http://localhost:4000"

auto: true
server: true
exclude: ['README.md', 'sass/']

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true