name: "HugoGiraudel.com"
description: "I write about front-end development stuff."
url: "http://localhost:4000"
future: false

auto: true
server: true

paginate: 7

markdown: rdiscount
permalink: pretty
pygments: true